### PR TITLE
Transaction Implementation

### PR DESCRIPTION
**Pull request by tremainebuchanan**
This pull request resolves issues #89.

### CODE REVIEW

**Comment by matjames007** [comment]
I am a little confused.... On the demand listing page you will notice that there exist a supply that matches the selected demand:
screen shot 2015-08-18 at 10 45 51 pm

However, when I go to the demand page it isn't listed in the supply card.  
screen shot 2015-08-18 at 10 45 58 pm

What is the thinking here?

**Comment by tremainebuchanan** [comment]
Not sure why it would behaving in that manner as the thought is once a supply becomes apart of a transaction, the supply is unavailable for another transaction to take place with that same supply. Can you provide the steps you took to get that result?

**Comment by matjames007** [comment]
@tremainebuchanan: The supply can be matched with multiple demands irrespective of any transactions currently in progress.  @paradoxxjm please confirm.  It is only until after a transaction has been closed that this is no longer true.

**Comment by tremainebuchanan** [comment]
@matjames007 @paradoxxjm has confirmed that the supply can be matched with multiple demands irrespective of any transactions currently in progress.

**Comment by matjames007** [comment]
I think I am satisfied with this pull request.  I am triggering the merge with this comment!

**Pull request closed without merging**
