### PR TITLE
Welcome and user approval emails revamped

### PR DESCRIPTION
**Pull request by tremainebuchanan**

### CODE REVIEW

**Comment by matjames007** [comment]
In your comment section please be sure to give some detail about the pull request.  The title alone isn't sufficient.  Why the revamp?  What was wrong with it before?  What is the thinking behind the change?  Who does it benefit?  When should this be rolled out? etc...

**Comment by tremainebuchanan** [comment]
@matjames007 my bad. coder fatigue. Prior to this change, we had a simple text email that was mediocre. I added some user friendly elements such as a button to allow easy access for the new user to the application and general email tone and voice.

**Comment by matjames007** [comment]
You might want to check this out: 
screen shot 2015-10-10 at 4 30 46 pm

**Comment by tremainebuchanan** [comment]
@matjames007 forgot to mention that there should be another environmental variable LOGIN_URL=http://localhost:3000/login that was added.

**Comment by matjames007** [comment]
Why not let the application dictate what the login url is?

**Comment by tremainebuchanan** [comment]
@matjames007 the last push ensures the application determines the login url.

**Pull request merged**
